import type { FC } from 'react';

interface Feature {
  icon: string;
  title: string;
  description: string;
}

const features: Feature[] = [
  {
    icon: 'quiz',
    title: 'Automated Questionnaires',
    description:
      'Intelligent data gathering that adapts to your system architecture automatically. No more manual security forms.',
  },
  {
    icon: 'assignment_turned_in',
    title: 'AI-Generated Reports',
    description:
      'Receive instant, actionable security insights and compliance documentation generated by our proprietary AI auditor.',
  },
  {
    icon: 'currency_bitcoin',
    title: 'Token-based Payments',
    description:
      'Frictionless billing and resource allocation through native OpenClaw token integration. Pay only for what you audit.',
  },
];

export const FeaturesSection: FC = () => {
  return (
    <section
      className="bg-white dark:bg-gray-900/50 py-24 border-y border-[#f0f2f4] dark:border-gray-800"
      id="features"
    >
      <div className="max-w-[1200px] mx-auto px-6">
        <div className="text-center mb-16 space-y-4">
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight">
            Enterprise-Grade Security Features
          </h2>
          <p className="text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
            Everything you need to ensure your AI systems remain secure,
            compliant, and optimized for maximum uptime.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="p-8 rounded-2xl bg-background-light dark:bg-background-dark border border-gray-100 dark:border-gray-800 hover:border-primary/30 transition-all group"
            >
              <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center text-primary mb-6 group-hover:bg-primary group-hover:text-white transition-all">
                <span className="material-symbols-outlined">{feature.icon}</span>
              </div>
              <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed text-sm">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
